version: '3.8'

services:
  iot_device_1:
    container_name: iot_device_1
    image: iot
    environment:
      - SET_NUMBER=1
      - IOT_ID=1
    volumes:
      - ./times:/app/times
    ports:
      - "5001:5000"

  iot_device_2:
    container_name: iot_device_2
    image: iot
    environment:
      - SET_NUMBER=2
      - IOT_ID=2
    volumes:
      - ./times:/app/times
    ports:
      - "5002:5000"

  iot_device_3:
    container_name: iot_device_3
    image: iot
    environment:
      - SET_NUMBER=3
      - IOT_ID=3
    volumes:
      - ./times:/app/times
    ports:
      - "5003:5000"

  iot_device_4:
    container_name: iot_device_4
    image: iot
    environment:
      - SET_NUMBER=4
      - IOT_ID=4
    volumes:
      - ./times:/app/times
    ports:
      - "5004:5000"

  iot_device_5:
    container_name: iot_device_5
    image: iot
    environment:
      - SET_NUMBER=5
      - IOT_ID=5
    volumes:
      - ./times:/app/times
    ports:
      - "5005:5000"